telegram:
  bot:
    name: ${rzd.bot.name.value}
    token: ${rzd.bot.token.value}

server:
  port: 8081

rzd:
  api:
    search:
      station:
        code: https://pass.rzd.ru/suggester?stationNamePart={stationName}&lang=ru&compactMode=y
        test: /&rid={rid}&SESSION_ID={sid}


